export const countries = [
    { code: "AF", name: "Afghanistan", image: "" },
    { code: "AX", name: "Åland Islands", image: "" },
    { code: "AL", name: "Albania", image: "" },
    { code: "DZ", name: "Algeria", image: "" },
    { code: "AS", name: "American Samoa", image: "" },
    { code: "AD", name: "Andorra", image: "" },
    { code: "AO", name: "Angola", image: "" },
    { code: "AI", name: "Anguilla", image: "" },
    { code: "AQ", name: "Antarctica", image: "" },
    { code: "AG", name: "Antigua and Barbuda", image: "" },
    { code: "AR", name: "Argentina", image: "" },
    { code: "AM", name: "Armenia", image: "" },
    { code: "AW", name: "Aruba", image: "" },
    { code: "AU", name: "Australia", image: "" },
    { code: "AT", name: "Austria", image: "" },
    { code: "AZ", name: "Azerbaijan", image: "" },
    { code: "BS", name: "Bahamas", image: "" },
    { code: "BH", name: "Bahrain", image: "" },
    { code: "BD", name: "Bangladesh", image: "" },
    { code: "BB", name: "Barbados", image: "" },
    { code: "BY", name: "Belarus", image: "" },
    { code: "BE", name: "Belgium", image: "" },
    { code: "BZ", name: "Belize", image: "" },
    { code: "BJ", name: "Benin", image: "" },
    { code: "BM", name: "Bermuda", image: "" },
    { code: "BT", name: "Bhutan", image: "" },
    { code: "BO", name: "Bolivia", image: "" },
    { code: "BA", name: "Bosnia and Herzegovina", image: "" },
    { code: "BW", name: "Botswana", image: "" },
    { code: "BV", name: "Bouvet Island", image: "" },
    { code: "BR", name: "Brazil", image: "" },
    { code: "IO", name: "British Indian Ocean Territory", image: "" },
    { code: "BN", name: "Brunei Darussalam", image: "" },
    { code: "BG", name: "Bulgaria", image: "" },
    { code: "BF", name: "Burkina Faso", image: "" },
    { code: "BI", name: "Burundi", image: "" },
    { code: "KH", name: "Cambodia", image: "" },
    { code: "CM", name: "Cameroon", image: "" },
    { code: "CA", name: "Canada", image: "" },
    { code: "CV", name: "Cape Verde", image: "" },
    { code: "KY", name: "Cayman Islands", image: "" },
    { code: "CF", name: "Central African Republic", image: "" },
    { code: "TD", name: "Chad", image: "" },
    { code: "CL", name: "Chile", image: "" },
    { code: "CN", name: "China", image: "" },
    { code: "CX", name: "Christmas Island", image: "" },
    { code: "CC", name: "Cocos (Keeling) Islands", image: "" },
    { code: "CO", name: "Colombia", image: "" },
    { code: "KM", name: "Comoros", image: "" },
    { code: "CG", name: "Congo", image: "" },
    { code: "CD", name: "Congo, Democratic Republic", image: "" },
    { code: "CK", name: "Cook Islands", image: "" },
    { code: "CR", name: "Costa Rica", image: "" },
    { code: "CI", name: "Cote D'Ivoire", image: "" },
    { code: "HR", name: "Croatia", image: "" },
    { code: "CU", name: "Cuba", image: "" },
    { code: "CY", name: "Cyprus", image: "" },
    { code: "CZ", name: "Czech Republic", image: "" },
    { code: "DK", name: "Denmark", image: "" },
    { code: "DJ", name: "Djibouti", image: "" },
    { code: "DM", name: "Dominica", image: "" },
    { code: "DO", name: "Dominican Republic", image: "" },
    { code: "EC", name: "Ecuador", image: "" },
    { code: "EG", name: "Egypt", image: "" },
    { code: "SV", name: "El Salvador", image: "" },
    { code: "GQ", name: "Equatorial Guinea", image: "" },
    { code: "ER", name: "Eritrea", image: "" },
    { code: "EE", name: "Estonia", image: "" },
    { code: "ET", name: "Ethiopia", image: "" },
    { code: "FK", name: "Falkland Islands", image: "" },
    { code: "FO", name: "Faroe Islands", image: "" },
    { code: "FJ", name: "Fiji", image: "" },
    { code: "FI", name: "Finland", image: "" },
    { code: "FR", name: "France", image: "" },
    { code: "GF", name: "French Guiana", image: "" },
    { code: "PF", name: "French Polynesia", image: "" },
    { code: "TF", name: "French Southern Territories", image: "" },
    { code: "GA", name: "Gabon", image: "" },
    { code: "GM", name: "Gambia", image: "" },
    { code: "GE", name: "Georgia", image: "" },
    { code: "DE", name: "Germany", image: "" },
    { code: "GH", name: "Ghana", image: "" },
    { code: "GI", name: "Gibraltar", image: "" },
    { code: "GR", name: "Greece", image: "" },
    { code: "GL", name: "Greenland", image: "" },
    { code: "GD", name: "Grenada", image: "" },
    { code: "GP", name: "Guadeloupe", image: "" },
    { code: "GU", name: "Guam", image: "" },
    { code: "GT", name: "Guatemala", image: "" },
    { code: "GG", name: "Guernsey", image: "" },
    { code: "GN", name: "Guinea", image: "" },
    { code: "GW", name: "Guinea-Bissau", image: "" },
    { code: "GY", name: "Guyana", image: "" },
    { code: "HT", name: "Haiti", image: "" },
    { code: "HM", name: "Heard Island & Mcdonald Islands", image: "" },
    { code: "VA", name: "Holy See (Vatican City State)", image: "" },
    { code: "HN", name: "Honduras", image: "" },
    { code: "HK", name: "Hong Kong", image: "" },
    { code: "HU", name: "Hungary", image: "" },
    { code: "IS", name: "Iceland", image: "" },
    { code: "IN", name: "India", image: "" },
    { code: "ID", name: "Indonesia", image: "" },
    { code: "IR", name: "Iran", image: "" },
    { code: "IQ", name: "Iraq", image: "" },
    { code: "IE", name: "Ireland", image: "" },
    { code: "IM", name: "Isle Of Man", image: "" },
    { code: "IL", name: "Israel", image: "" },
    { code: "IT", name: "Italy", image: "" },
    { code: "JM", name: "Jamaica", image: "" },
    { code: "JP", name: "Japan", image: "" },
    { code: "JE", name: "Jersey", image: "" },
    { code: "JO", name: "Jordan", image: "" },
    { code: "KZ", name: "Kazakhstan", image: "" },
    { code: "KE", name: "Kenya", image: "" },
    { code: "KI", name: "Kiribati", image: "" },
    { code: "KR", name: "Korea", image: "" },
    { code: "KW", name: "Kuwait", image: "" },
    { code: "KG", name: "Kyrgyzstan", image: "" },
    { code: "LA", name: "Lao People's Democratic Republic", image: "" },
    { code: "LV", name: "Latvia", image: "" },
    { code: "LB", name: "Lebanon", image: "" },
    { code: "LS", name: "Lesotho", image: "" },
    { code: "LR", name: "Liberia", image: "" },
    { code: "LY", name: "Libyan Arab Jamahiriya", image: "" },
    { code: "LI", name: "Liechtenstein", image: "" },
    { code: "LT", name: "Lithuania", image: "" },
    { code: "LU", name: "Luxembourg", image: "" },
    { code: "MO", name: "Macao", image: "" },
    { code: "MK", name: "Macedonia", image: "" },
    { code: "MG", name: "Madagascar", image: "" },
    { code: "MW", name: "Malawi", image: "" },
    { code: "MY", name: "Malaysia", image: "" },
    { code: "MV", name: "Maldives", image: "" },
    { code: "ML", name: "Mali", image: "" },
    { code: "MT", name: "Malta", image: "" },
    { code: "MH", name: "Marshall Islands", image: "" },
    { code: "MQ", name: "Martinique", image: "" },
    { code: "MR", name: "Mauritania", image: "" },
    { code: "MU", name: "Mauritius", image: "" },
    { code: "YT", name: "Mayotte", image: "" },
    { code: "MX", name: "Mexico", image: "" },
    { code: "FM", name: "Micronesia", image: "" },
    { code: "MD", name: "Moldova", image: "" },
    { code: "MC", name: "Monaco", image: "" },
    { code: "MN", name: "Mongolia", image: "" },
    { code: "ME", name: "Montenegro", image: "" },
    { code: "MS", name: "Montserrat", image: "" },
    { code: "MA", name: "Morocco", image: "" },
    { code: "MZ", name: "Mozambique", image: "" },
    { code: "MM", name: "Myanmar", image: "" },
    { code: "NA", name: "Namibia", image: "" },
    { code: "NR", name: "Nauru", image: "" },
    { code: "NP", name: "Nepal", image: "" },
    { code: "NL", name: "Netherlands", image: "" },
    { code: "AN", name: "Netherlands Antilles", image: "" },
    { code: "NC", name: "New Caledonia", image: "" },
    { code: "NZ", name: "New Zealand", image: "" },
    { code: "NI", name: "Nicaragua", image: "" },
    { code: "NE", name: "Niger", image: "" },
    { code: "NG", name: "Nigeria", image: "" },
    { code: "NU", name: "Niue", image: "" },
    { code: "NF", name: "Norfolk Island", image: "" },
    { code: "MP", name: "Northern Mariana Islands", image: "" },
    { code: "NO", name: "Norway", image: "" },
    { code: "OM", name: "Oman", image: "" },
    { code: "PK", name: "Pakistan", image: "" },
    { code: "PW", name: "Palau", image: "" },
    { code: "PS", name: "Palestine", image: "" },
    { code: "PA", name: "Panama", image: "" },
    { code: "PG", name: "Papua New Guinea", image: "" },
    { code: "PY", name: "Paraguay", image: "" },
    { code: "PE", name: "Peru", image: "" },
    { code: "PH", name: "Philippines", image: "" },
    { code: "PN", name: "Pitcairn", image: "" },
    { code: "PL", name: "Poland", image: "" },
    { code: "PT", name: "Portugal", image: "" },
    { code: "PR", name: "Puerto Rico", image: "" },
    { code: "QA", name: "Qatar", image: "" },
    { code: "RE", name: "Reunion", image: "" },
    { code: "RO", name: "Romania", image: "" },
    { code: "RU", name: "Russian Federation", image: "" },
    { code: "RW", name: "Rwanda", image: "" },
    { code: "BL", name: "Saint Barthelemy", image: "" },
    { code: "SH", name: "Saint Helena", image: "" },
    { code: "KN", name: "Saint Kitts And Nevis", image: "" },
    { code: "LC", name: "Saint Lucia", image: "" },
    { code: "MF", name: "Saint Martin (French part)", image: "" },
    { code: "SX", name: "Sint Maarten (Dutch part)", image: "" },
    { code: "ST", name: "Sao Tome and Principe", image: "" },
    { code: "SA", name: "Saudi Arabia", image: "" },
    { code: "SN", name: "Senegal", image: "" },
    { code: "RS", name: "Serbia", image: "" },
    { code: "SC", name: "Seychelles", image: "" },
    { code: "SL", name: "Sierra Leone", image: "" },
    { code: "SG", name: "Singapore", image: "" },
    { code: "SK", name: "Slovakia", image: "" },
    { code: "SI", name: "Slovenia", image: "" },
    { code: "SB", name: "Solomon Islands", image: "" },
    { code: "SO", name: "Somalia", image: "" },
    { code: "ZA", name: "South Africa", image: "" },
    { code: "GS", name: "South Georgia and the South Sandwich Islands", image: "" },
    { code: "ES", name: "Spain", image: "" },
    { code: "LK", name: "Sri Lanka", image: "" },
    { code: "SD", name: "Sudan", image: "" },
    { code: "SR", name: "Suriname", image: "" },
    { code: "SJ", name: "Svalbard and Jan Mayen", image: "" },
    { code: "SZ", name: "Swaziland", image: "" },
    { code: "SE", name: "Sweden", image: "" },
    { code: "CH", name: "Switzerland", image: "" },
    { code: "SY", name: "Syrian Arab Republic", image: "" },
    { code: "TW", name: "Taiwan", image: "" },
    { code: "TJ", name: "Tajikistan", image: "" },
    { code: "TZ", name: "Tanzania", image: "" },
    { code: "TH", name: "Thailand", image: "" },
    { code: "TL", name: "Timor-Leste", image: "" },
    { code: "TG", name: "Togo", image: "" },
    { code: "TK", name: "Tokelau", image: "" },
    { code: "TO", name: "Tonga", image: "" },
    { code: "TT", name: "Trinidad and Tobago", image: "" },
    { code: "TN", name: "Tunisia", image: "" },
    { code: "TR", name: "Turkey", image: "" },
    { code: "TM", name: "Turkmenistan", image: "" },
    { code: "TC", name: "Turks and Caicos Islands", image: "" },
    { code: "TV", name: "Tuvalu", image: "" },
    { code: "UG", name: "Uganda", image: "" },
    { code: "UA", name: "Ukraine", image: "" },
    { code: "AE", name: "United Arab Emirates", image: "" },
    { code: "GB", name: "United Kingdom", image: "" },
    { code: "US", name: "United States", image: "" },
    { code: "UM", name: "United States Minor Outlying Islands", image: "" },
    { code: "UY", name: "Uruguay", image: "" },
    { code: "UZ", name: "Uzbekistan", image: "" },
    { code: "VU", name: "Vanuatu", image: "" },
    { code: "VE", name: "Venezuela", image: "" },
    { code: "VN", name: "Viet Nam", image: "" },
    { code: "VG", name: "Virgin Islands, British", image: "" },
    { code: "VI", name: "Virgin Islands, U.S.", image: "" },
    { code: "WF", name: "Wallis and Futuna", image: "" },
    { code: "EH", name: "Western Sahara", image: "" },
    { code: "YE", name: "Yemen", image: "" },
    { code: "ZM", name: "Zambia", image: "" },
    { code: "ZW", name: "Zimbabwe", image: "" }
];
